### ISSUE TITLE
[ BUG] Alarmio got crashed when I clicked 'OSS Licences'

### ISSUE THREAD

**Issue by peerzadaaabid** [fennifith/Alarmio#58] opened 2019-07-03 15:58 UTC
## Device Info

- Brand: 'Mi'

- Android version: `7.0

## Steps to Reproduce

- download the app
- Click on 'OSS Licences'
- see bug

Recording of bug
https://youtu.be/SPkZQPB4Tv4

**Comment by fennifith** [comment] 2019-07-03 15:59
This is a duplicate of #47.

**Closed** 2019-07-03 15:59 UTC
Labels: duplicate
