### ISSUE TITLE
Alarm volume set to zero

### ISSUE THREAD

**Issue by woodruffandtheschnibbleofazimuth** [fennifith/Alarmio#84] opened 2019-11-04 08:03 UTC
After two days of no waking up because the alarm does not start i have made several test to understand why. Everytime Alarmio starts the volume of alarn on the phone goes to zero.
So it just vibrate!
I have tried during the day some test: volume up on alarm. Set an alarm during next minutes. The alarm start but is mute, check the volume and is zero.
Am i the only with this issue?

Android 9.0
Emui 9.1.0
Huawei P20 Pro

**Comment by fennifith** [comment] 2019-11-04 15:17
The "slow wake-up" feature will reset the volume whenever an alarm rings; if it has a long duration, it's possible that the alarm sound might not be noticeable for the first few seconds. Is it possible that's what is happening here?

**Comment by fennifith** [comment] 2019-11-11 21:37
Other users have reported that this is working as it should; I'll leave this open for a few days, then close if there are no more issues.

**Comment by andreaguani** [comment] 2019-11-12 16:16
Hi fennifith, sorry for the delay.
I have made other test and yes, it was the "slow wake-up".

The problem was that i set "Slow wake-up duration" at 5 minutes but i don't consider it because i set to no the "Slow wake-up" feature. If i set the duration to '1 sec' it works.

But it seems to ignore the on/off setting of the "Slow Wake-up" :)

Thanks for the help,

**Comment by jimbo1qaz** [comment] 2019-12-05 01:27
>But it seems to ignore the on/off setting of the "Slow Wake-up" :)
The issue is that when the app data is cleared, the Slow Wake-up option is unchecked visually, but the program acts like it's checked. This can be fixed by toggling it on and off again.

**Comment by raboof** [comment] 2019-12-29 13:19
> when the app data is cleared, the Slow Wake-up option is unchecked visually, but the program acts like it's checked. This can be fixed by toggling it on and off again

I saw this as well

**Comment by infinitewaveparticle** [comment] 2020-01-13 21:55
The problem with this on my device (Samsung Galaxy S7 Edge running stock Android 8) is far greater. When I first installed the latest update (1.0.4) the sound worked (when choosing an alarm sound and clicking the Play buttons beside them), but after setting the alarm and turning on the slow wake up feature (which never made a sound whatsoever when the alarm went off so clearly that is a bug too) nothing I can do will even get the app to make a sound PERIOD. When setting up a new alarm and choosing a sound the little Play buttons next to each sound don't play any audible sound now. Force-closing, clearing the app data, toggling the slow wake up feature - done in any order - does not help. Sounds work in every other app and my volume levels are all at MAX. The only thing I haven't tried is uninstalling and reinstalling, but it would be nice if these whole slow wake up and sound bugs (critical) would be permanently fixed. After all the whole point of any alarm clock is to play sounds at set times.

**Comment by andrewsno1** [comment] 2020-01-13 22:42
> The problem with this on my device (Samsung Galaxy S7 Edge running stock Android 8) is far greater. When I first installed the latest update (1.0.4) the sound worked (when choosing an alarm sound and clicking the Play buttons beside them), but after setting the alarm and turning on the slow wake up feature (which never made a sound whatsoever when the alarm went off so clearly that is a bug too) nothing I can do will even get the app to make a sound PERIOD. When setting up a new alarm and choosing a sound the little Play buttons next to each sound don't play any audible sound now. Force-closing, clearing the app data, toggling the slow wake up feature - done in any order - does not help. Sounds work in every other app and my volume levels are all at MAX. The only thing I haven't tried is uninstalling and reinstalling, but it would be nice if these whole slow wake up and sound bugs (critical) would be permanently fixed. After all the whole point of any alarm clock is to play sounds at set times.
> 
> Note: Other alarm clocks work for me on my device so there's no issue there.

I have exactly the same issue. I tried reinstalling but it did not help.
LG G5, LG Android 8

**Comment by raboof** [comment] 2020-01-14 06:56
Would you be interested in trying a build of AlarmIO that has extra diagnostic logging enabled and sharing those logs (possibly privately)?

I don't see this problem (aside from having had to toggle Slow Wake-up to disable it) but I like AlarmIO so I'd be willing to help. Pretty busy time for me ahead though, so it might take a while ;).

**Comment by infinitewaveparticle** [comment] 2020-01-15 22:50
Sure!

-------- Original Message --------

**Comment by tokenmath** [comment] 2020-01-29 05:08
It is a very interesting bug because after deactivating the volume control of the alarm it returned to work (except that some rings are still not reproduced)

**Comment by b3nks** [comment] 2020-02-15 02:11
I had the same issue, Alarmio basically playing the sound but at volume zero, on my Samsung Galaxy A5 (2017).
I fixed it in one step by changing a 
Settings - Apps - Alarmio - "Notification" - "Timers - no sound" - "Importance Medium no Sound" switched to "Urgent".

Now the sound is audible.

**Comment by ajayyy** [comment] 2020-03-26 15:20
I think this is because some phones have very few volume steps, so the app remains at zero volume until the slow wakeup is complete.

**Comment by ajayyy** [comment] 2020-03-26 19:24
Assigning myself to this

**Comment by fennifith** [comment] 2020-04-09 22:29
[`1.0.5`](https://github.com/fennifith/Alarmio/releases/tag/1.0.5) was just released - hopefully this should now be fixed... (please re-open if not)

Also, something I only just thought of: maybe it'd be a good idea to _not_ have the `SLOW_WAKE_UP` setting enabled by default? It seems like it might cause some confusion, regardless of whether the issue is present...

**Closed by fennifith** 2020-04-09 22:29 UTC
