### ISSUE TITLE
(Bug) App stops working

### ISSUE THREAD

**Issue by tokenmath** [fennifith/Alarmio#94] opened 2020-01-28 05:19 UTC
It stops working out of nowhere and doesn't work as it should

**Comment by fennifith** [comment] 2020-03-30 18:12
There isn't enough information here for me to tell what you're doing or reproduce the issue. It sounds like this is a duplicate of #45, but I can't work out what the issue is with this little detail. For now I'll assume this is a duplicate of an existing issue and close it; feel free to re-open if that is not the case.

**Closed by fennifith** 2020-03-30 18:12 UTC
