### ISSUE TITLE
App Crashes: java.lang.RuntimeException at TimerReceiver.java:18
java.lang.RuntimeException

### ISSUE THREAD

**Issue by abdrysdale** [fennifith/Alarmio#140] opened 2020-09-29 07:32 UTC
```
java.lang.RuntimeException: Unable to start receiver me.jfenn.alarmio.receivers.TimerReceiver: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3798)
	at android.app.ActivityThread.access$1400(ActivityThread.java:220)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1871)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at me.jfenn.alarmio.receivers.TimerReceiver.onReceive(TimerReceiver.java:18)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3789)
	... 8 more


Android Version: 29
Device Manufacturer: Fairphone
Device Model: FP3
```

Love the app!

**Comment by shroff** [comment] 2020-10-27 00:53
+1 Gonna try looking into it.

**Comment by fennifith** [comment] 2020-12-08 20:11
Duplicate of #123 :)

**Closed by fennifith** 2020-12-08 20:11 UTC
Labels: duplicate
