### ISSUE TITLE
Does not work in the background

### ISSUE THREAD

**Issue by scottymedia** [fennifith/Alarmio#85] opened 2019-11-16 23:23 UTC
When the app is closed, the alarm won't fire even if it is set on.

When the app is in the background, the alarm won't fire even if it is set on.

**Comment by raboof** [comment] 2019-12-06 11:30
Did you configure "Ignore Battery Optimizations" in the Settings?

**Comment by Akruidenberg** [comment] 2019-12-28 08:02
Same for me. Ignore Battery Optimizations" is set

**Comment by raboof** [comment] 2019-12-28 13:14
Interesting, haven't seen that yet (but admittedly I haven't been using Alarmio intensely yet). Can you reliably reproduce it? How? On what Android version, what kind of phone etc?

**Comment by fennifith** [comment] 2019-12-30 04:35
No idea what's going on here without more info, but these issues are so annoyingly common between apps that it's likely not a problem with Alarmio (though the possibility of in-app fixes is still valid). I've been meaning to add a distinct "intro screen" to explain some of this to new users - [dontkillmyapp.com](https://dontkillmyapp.com/) covers most of the ways that this can be prevented on various devices.

I'm planning to implement [doki](https://github.com/doubledotlabs/doki) as a part of an onboarding screen to show instructions, as well as moving the "Ignore Battery Optimizations" higher up in the settings menu (and adding a check box to visually show if it's enabled, since some devices will disable it on reboot).

It would be nice if Alarmio could detect this behavior and warn the user before setting an alarm (accidentally making someone late to work is _not_ something that I want to feel responsible for), but I don't know of any feasible way to do that.

**Comment by rien333** [comment] 2020-03-30 18:38
So setting "Ignore Battery Optimizations" to an appropiate value works for some users?

**Comment by fennifith** [comment] 2020-03-30 18:48
@rien333 I believe it varies between devices; ignoring battery optimizations did not work for a lot of users, while for a couple others it seems like it did. I'm hoping that `SYSTEM_ALERT_WINDOW` will solve the issue for everyone else. To be on the safe side, Alarmio probably needs both in order to function properly.

I'm hoping to have a better UI for prompting users to grant these permissions in the future, maybe implementing [doubledotlabs/doki](https://github.com/doubledotlabs/doki) to actually walk users through all of these options once it's at a more polished state.

**Comment by AndroidDeveloperLB** [comment] 2020-03-30 18:58
@fennifith No need for any permission. See my post here:
https://github.com/fennifith/Alarmio/issues/100#issuecomment-606179646

**Comment by AndroidDeveloperLB** [comment] 2020-04-01 06:58
@fennifith Just so you know, I tried the build from dev on emulator with API 27. 
I've set it to work 1 minute from the current time, and granted it SAW permission.
Then I turned off the screen, and nothing appeared or made a sound, even after I turned on the screen.
See attached video and project.

[check.zip](https://github.com/fennifith/Alarmio/files/4413277/check.zip)

**Comment by fennifith** [comment] 2020-04-01 15:37
@AndroidDeveloperLB Just reproduced this myself - checking the logcat, the activity is actually opening, but the app force-closes before the device wakes up due to a NullPointerException because there is no alarm ringtone set - fixed in c65aa0f. I must've missed this being a problem somehow.

I can verify (albeit through an emulator) that it does work properly now. It is evident that more testing is needed before the next release, though.

**Comment by fennifith** [comment] 2020-04-09 22:35
Alright, the SAW workaround is in [`1.0.5`](https://github.com/fennifith/Alarmio/releases/tag/1.0.5) - hopefully that work for most users until #107 can be implemented.

**Closed by fennifith** 2020-04-09 22:35 UTC
Labels: bug

**Comment by AndroidDeveloperLB** [comment] 2020-04-09 22:39
OK if you wish to see how to implement it "according to the book", check the other thread, and please ignore the misunderstanding of what I tried to explain.
You can ask me anything if you wish for my help. I will try my best. :)

**Comment by rien333** [comment] 2020-04-09 23:29
Thanks for the workaround, setting the extra permission that alarmio 1.0.5 now requests did seem to help. 

However, there seem to a be a couple of crashes that I can trigger after this update. As a specific example, after selecting a snooze range (e.g. 2min) during an alarm, the app now crashes. (not sure if you can reproduce tho) 

The error I'm getting is an `indexOutOfBounds` error. I'm going to bed now, but if you can reproduce I can open a new issue with a proper log.
