### ISSUE TITLE
App  gets killed by android system

### ISSUE THREAD

**Issue by sharma-harshit** [fennifith/Alarmio#42] opened 2019-02-24 18:30 UTC
## Device Info

- Brand: `Samsunokiapplackberriaomissentialg`
- Model name: `John Doe`
- Android version: `Stock, hopefully.`

## Steps to Reproduce

- download the app
- hop on your left foot three times
- turn 90 degrees counterclockwise
- head, shoulders knees and toes knees and toes knees and toes knees and toes knees and toes knees and toes knees and toes knees and toes knees and toes

**Comment by fennifith** [comment] 2019-02-24 19:21
Could you please provide more information? When does the crash occur, what device are you using, are there any consistencies in when it stops working? Is this an actual error in the app or a duplicate of #37?

**Comment by sharma-harshit** [comment] 2019-02-24 19:35
I am really very sorry.
I am a noobie to GitHub, I didn't know how post things and contact the repo Manager.
Actually, I am working on a similar project (learning purpose only) and I was also using Alarm Manager for that but my app gets killed by the Android system and hence Iwanted to know that how your app is managing that?

**Comment by fennifith** [comment] 2019-02-24 21:43
Sorry for the late reply, took me a while to type this all out. There are a few different ways to prevent your app from being killed - it somewhat depends on knowing more about why the app is killed (hence needing more information), but if you're using the `AlarmManager` with `.setAlarmClock` it _should_ start your app again when it is time for the alarm regardless of the situation. The app should **not** constantly be in the foreground whenever there is an alarm set, as this will only create unnecessary battery drain.

On devices where `.setAlarmClock` is not supported, you should use `.setExact` or `.set` with the [`RTC_WAKEUP`](https://developer.android.com/reference/android/app/AlarmManager#RTC_WAKEUP) flag, and send a broadcast to `android.intent.action.ALARM_CHANGED` to notify the system that an alarm has been created. You can find my implementation of all of this [here](https://github.com/fennifith/Alarmio/blob/564e86aa7f8dbe09a0cb28d79fa3ff0f92b3db7b/app/src/main/java/me/jfenn/alarmio/data/AlarmData.java#L282).

If your app is killed in a situation where it should be running (ex: a timer that needs to stay active if the user switches to a different app), I would look into creating a [foreground service](https://developer.android.com/guide/components/services) to handle whatever task it needs to do; this is how I made Alarmio's stopwatch and timer. If you've done this and it is _still_ being killed, it's likely a device-specific edge case that isn't really supposed to happen, and you should look through [https://dontkillmyapp.com/](https://dontkillmyapp.com/) for a solution (though there isn't much you can do to prevent it in the app).

Finally, if you find that your alarms are being lost whenever the device is shut down, that's because they are; you'll need to declare the [`RECEIVE_BOOT_COMPLETED`](https://developer.android.com/reference/android/Manifest.permission.html#RECEIVE_BOOT_COMPLETED) permission and re-create your alarms (assuming you've stored them in `SharedPreferences` or in a database somewhere) in a `BroadcastReceiver`. You can find my implementation of this [here](https://github.com/fennifith/Alarmio/blob/564e86aa7f8dbe09a0cb28d79fa3ff0f92b3db7b/app/src/main/java/me/jfenn/alarmio/receivers/RestoreOnBootReceiver.java), with the intent-filter declared in the manifest [here](https://github.com/fennifith/Alarmio/blob/564e86aa7f8dbe09a0cb28d79fa3ff0f92b3db7b/app/src/main/AndroidManifest.xml#L47).

**Comment by fennifith** [comment] 2019-02-24 22:06
As to your use of github, this is actually fine. Issues are normally used to report problems / errors with the project, and the title was a little vague so I assumed it was an issue with the app. But they work fine for questions, too (there is a "question" label for this purpose). You could even use them to share [pictures of cats](http://www.cutestpaw.com/tag/cats/) in most projects with few complaints. For contacting the owner directly, you can click on my username or go to `https://github.com/fennifith` to find my contact info, but creating an issue is usually preferred as it keeps the discussion open to other people.

Alternatively, if you use Discord, clicking on the "chat" button on the main page of the project will take you to https://discord.jfenn.me/ where you can message me or other people that work on the project and likely get a faster answer.

**Comment by fennifith** [comment] 2019-03-01 05:05
Closing this due to inactivity. Let me know if you need any more help :)

**Closed by fennifith** 2019-03-01 05:05 UTC
Labels: question

**Comment by sharma-harshit** [comment] 2019-03-02 17:40
Sorry for late reply.
Thank you so much for the help.
I would like to contact you.
Please provide any Whatsapp,Telegram, Slack or any other platform information to connect. I am sorry but I don't use Discord if you don't have any other way then I would make an account.

**Comment by fennifith** [comment] 2019-03-02 17:51
@sharma-harshit https://t.me/fennifith

**Comment by sharma-harshit** [comment] 2019-03-02 17:57
Thank you

**Comment by ibrahimAlii** [comment] 2019-08-23 00:18
@fennifith The @sharma-harshit point is valid, If you removed your app from recent apps on devices like: OPPO, xiaomi and most of chinese phones then the alarm won't triggered !
