### ISSUE TITLE
App crashes when screen is being rotated to landscape mode

### ISSUE THREAD

**Issue by keksimusmaximus** [fennifith/Alarmio#132] opened 2020-06-21 07:42 UTC
## Device Info

- Brand: `Fairphone`
- Model name: `3`
- Android version: ` IMG-e-0.9-p-2020061158052-dev-FP3`

## Steps to Reproduce

- start timer
- rotate phone 
- wait for crash report

Here is a record of the problem:
[https://streamable.com/wbd1sv](url)

> java.lang.IndexOutOfBoundsException at AlarmsAdapter.kt:450
> java.lang.IndexOutOfBoundsException
> 
> java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
>  at java.util.ArrayList.get(ArrayList.java:437)
>  at me.jfenn.alarmio.adapters.AlarmsAdapter$AlarmViewHolder$1.afterTextChanged(AlarmsAdapter.kt:450)
>  at android.widget.TextView.sendAfterTextChanged(TextView.java:9787)
>  at android.widget.TextView.setText(TextView.java:5756)
>  at android.widget.TextView.setText(TextView.java:5588)
>  at android.widget.EditText.setText(EditText.java:122)
>  at android.widget.TextView.setText(TextView.java:5545)
>  at me.jfenn.alarmio.adapters.AlarmsAdapter.onBindAlarmViewHolder(AlarmsAdapter.kt:266)
>  at me.jfenn.alarmio.adapters.AlarmsAdapter.onBindViewHolder(AlarmsAdapter.kt:357)
>  at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
>  at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
>  at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
>  at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
>  at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
>  at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
>  at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
>  at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:561)
>  at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
>  at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
>  at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
>  at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
>  at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
>  at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
>  at android.view.View.layout(View.java:20693)
>  at android.view.ViewGroup.layout(ViewGroup.java:6194)
>  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
>  at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
>  at android.view.View.layout(View.java:20693)
>  at android.view.ViewGroup.layout(ViewGroup.java:6194)
>  at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
>  at android.view.View.layout(View.java:20693)
>  at android.view.ViewGroup.layout(ViewGroup.java:6194)
>  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
>  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
>  at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
>  at android.view.View.layout(View.java:20693)
>  at android.view.ViewGroup.layout(ViewGroup.java:6194)
>  at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
>  at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
>  at com.google.android.material.bottomsheet.BottomSheetBehavior.onLayoutChild(BottomSheetBehavior.java:380)
>  at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
>  at android.view.View.layout(View.java:20693)
>  at android.view.ViewGroup.layout(ViewGroup.java:6194)
>  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
>  at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
>  at android.view.View.layout(View.java:20693)
>  at android.view.ViewGroup.layout(ViewGroup.java:6194)
>  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
>  at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
>  at android.view.View.layout(View.java:20693)
>  at android.view.ViewGroup.layout(ViewGroup.java:6194)
>  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
>  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
>  at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
>  at android.view.V
> iew.layout(View.java:20693)
>  at android.view.ViewGroup.layout(ViewGroup.java:6194)
>  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
>  at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
>  at android.view.View.layout(View.java:20693)
>  at android.view.ViewGroup.layout(ViewGroup.java:6194)
>  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
>  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
>  at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
>  at android.view.View.layout(View.java:20693)
>  at android.view.ViewGroup.layout(ViewGroup.java:6194)
>  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
>  at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
>  at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)
>  at android.view.View.layout(View.java:20693)
>  at android.view.ViewGroup.layout(ViewGroup.java:6194)
>  at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2799)
>  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2316)
>  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1463)
>  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7190)
>  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
>  at android.view.Choreographer.doCallbacks(Choreographer.java:761)
>  at android.view.Choreographer.doFrame(Choreographer.java:696)
>  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
>  at android.os.Handler.handleCallback(Handler.java:873)
>  at android.os.Handler.dispatchMessage(Handler.java:99)
>  at android.os.Looper.loop(Looper.java:193)
>  at android.app.ActivityThread.main(ActivityThread.java:6718)
>  at java.lang.reflect.Method.invoke(Native Method)
>  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
>  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

Android Version: 28
Device Manufacturer: Fairphone
Device Model: FP3

**Comment by fennifith** [comment] 2020-06-25 02:33
Thanks for the crash report! This is already fixed in the repository; it'll be in the next release. Duplicate of #98

**Closed** 2020-06-25 02:33 UTC
Labels: duplicate
