### ISSUE TITLE
[Feature Request] Add some task to turn off alarm ?

### ISSUE THREAD

**Issue by azzamsa** [fennifith/Alarmio#46] opened 2019-04-28 04:38 UTC
As far as I search, there are some foss android alarm clock app out there, but this one seems the only one that up to date. In our foss android world right now we don't have any alternative to [alarmy](https://play.google.com/store/apps/details?id=droom.sleepIfUCan&hl=en) or [i can't wake up](http://kogcreations.com/android/). 

Do you have any intent to add some taks (.e.g math task, rewrite task, barcode task, etc)  to toggle off alarm ?

Thank you for alarmio

**Comment by azzamsa** [comment] 2019-04-28 04:47
Some example task from `I can't wake up`

![image](https://user-images.githubusercontent.com/17734314/56858853-4d606d80-69ab-11e9-95a2-33bf1d1d4a55.png)

**Comment by fennifith** [comment] 2019-06-17 21:32
I've been late responding to this. Thank you for your ideas. I am going to close this as a duplicate of #33, but will refer to it when I work on the issue.

**Closed** 2019-06-17 21:33 UTC
Labels: duplicate
