### ISSUE TITLE
After starting timer pressing back throws exception, timer disappears

### ISSUE THREAD

**Issue by madb1lly** [fennifith/Alarmio#122] opened 2020-04-30 08:15 UTC
## Device Info

- Brand: Nokia
- Model name: Nokia 8
- Android version: 9 stock

## Steps to Reproduce

1. Start a timer
2. Press back
3. Exception thrown and timer disappears

EDIT: This error also occurred after clicking back on crash #123 when that crash occurred after my instance of #113. This also happened when I snoozed an alarm whilst trying to replicate #113.

"Alarmio crashed. java.lang.IndexOutOfBoundsException at AlarmsAdapter.kt:450"

Stack trace:
```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.get(ArrayList.java:437)
	at me.jfenn.alarmio.adapters.AlarmsAdapter$AlarmViewHolder$1.afterTextChanged(AlarmsAdapter.kt:450)
	at android.widget.TextView.sendAfterTextChanged(TextView.java:9785)
	at android.widget.TextView.setText(TextView.java:5754)
	at android.widget.TextView.setText(TextView.java:5586)
	at android.widget.EditText.setText(EditText.java:122)
	at android.widget.TextView.setText(TextView.java:5543)
	at me.jfenn.alarmio.adapters.AlarmsAdapter.onBindAlarmViewHolder(AlarmsAdapter.kt:266)
	at me.jfenn.alarmio.adapters.AlarmsAdapter.onBindViewHolder(AlarmsAdapter.kt:357)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:561)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
	at android.view.View.layout(View.java:20715)
	at android.view.ViewGroup.layout(ViewGroup.java:6202)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20715)
	at android.view.ViewGroup.layout(ViewGroup.java:6202)
	at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
	at android.view.View.layout(View.java:20715)
	at android.view.ViewGroup.layout(ViewGroup.java:6202)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20715)
	at android.view.ViewGroup.layout(ViewGroup.java:6202)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
	at com.google.android.material.bottomsheet.BottomSheetBehavior.onLayoutChild(BottomSheetBehavior.java:380)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
	at android.view.View.layout(View.java:20715)
	at android.view.ViewGroup.layout(ViewGroup.java:6202)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20715)
	at android.view.ViewGroup.layout(ViewGroup.java:6202)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20715)
	at android.view.ViewGroup.layout(ViewGroup.java:6202)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20715)
	at android.view.ViewGroup.layout(ViewGroup.java:6202)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20715)
	at android.view.ViewGroup.layout(ViewGroup.java:6202)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20715)
	at android.view.ViewGroup.layout(ViewGroup.java:6202)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:903)
	at android.view.View.layout(View.java:20715)
	at android.view.ViewGroup.layout(ViewGroup.java:6202)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2812)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2339)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1479)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7258)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1050)
	at android.view.Choreographer.doCallbacks(Choreographer.java:862)
	at android.view.Choreographer.doFrame(Choreographer.java:797)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1036)
	at android.os.Handler.handleCallback(Handler.java:874)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:198)
	at android.app.ActivityThread.main(ActivityThread.java:6729)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)




```

**Comment by fennifith** [comment] 2020-05-04 21:21
Duplicate of #98 - different steps to reproduce, but the exception being thrown (and the underlying problem) is the same.

**Closed** 2020-05-04 21:22 UTC
Labels: duplicate
