### ISSUE TITLE
App crashes when 2 alarms are set and the first one is being turned off

### ISSUE THREAD

**Issue by keksimusmaximus** [fennifith/Alarmio#133] opened 2020-06-21 07:45 UTC
## Device Info

- Brand: `Fairphone`
- Model name: `3`
- Android version: ` IMG-e-0.9-p-2020061158052-dev-FP3`

## Steps to Reproduce

- set 2 alarms
- wait for 1st alarm to sound, turn it off
- wait for crash report

> 
> java.lang.RuntimeException: Unable to create application me.jfenn.alarmio.Alarmio: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=me.jfenn.alarmio/.services.TimerService }: app is in background uid UidRecord{33b09da u0a130 RCVR idle change:uncached procs:1 seq(0,0,0)}
>  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5925)
>  at android.app.ActivityThread.access$1100(ActivityThread.java:200)
>  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
>  at android.os.Handler.dispatchMessage(Handler.java:106)
>  at android.os.Looper.loop(Looper.java:193)
>  at android.app.ActivityThread.main(ActivityThread.java:6718)
>  at java.lang.reflect.Method.invoke(Native Method)
>  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
>  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
> Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=me.jfenn.alarmio/.services.TimerService }: app is in background uid UidRecord{33b09da u0a130 RCVR idle change:uncached procs:1 seq(0,0,0)}
>  at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1577)
>  at android.app.ContextImpl.startService(ContextImpl.java:1532)
>  at android.content.ContextWrapper.startService(ContextWrapper.java:664)
>  at me.jfenn.alarmio.Alarmio.onCreate(Alarmio.java:118)
>  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
>  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5920)
>  ... 8 more

**Comment by fennifith** [comment] 2020-06-25 02:36
Thanks for the crash report! This issue has already been reported - duplicate of #113

**Closed** 2020-06-25 02:36 UTC
Labels: duplicate
