### ISSUE TITLE
Renaming of alarms fail

### ISSUE THREAD

**Issue by breiti-oi** [fennifith/Alarmio#49] opened 2019-06-17 17:39 UTC
If you have more than 1 alarm and want to name every one of them, all get the same name in the end. If you try to delete the wrong name in the other alarm, all names change.

## Device Info

- Brand: `Essential Industries`
- Model name: `PH1`
- Android version: `AOSiP 9`

## Steps to Reproduce
- create more than one Alarm
- try to name one of them
- see how the others behave

**Comment by fennifith** [comment] 2019-06-17 21:29
I can't reproduce this on my end. It might have been unintentionally fixed in one of the commits since `1.0.1` and just hasn't been released yet, but I would have probably noticed if this was an issue during prior testing.

Could you possibly upload a screen recording of the issue or describe the steps in more detail? Thank you.

**Comment by breiti-oi** [comment] 2019-06-18 07:42
![ScreenRec_20190618_084257_tzw8c23dkx](https://user-images.githubusercontent.com/51925544/59662464-4553cb80-91ad-11e9-8e16-a68470bd30a6.gif)

**Comment by ikanakova** [comment] 2019-07-14 19:08
[same here](https://imgur.com/a/uLxwhPK)

**Comment by fennifith** [comment] 2019-10-16 01:54
This _should_ now be fixed in `1.0.3` (though I could never reproduce the issue, so I won't know). Ping me and I'll reopen if not.

**Closed by fennifith** 2019-10-16 01:54 UTC
Labels: bug
