### ISSUE TITLE
[Feature request] Dismiss alarm on shake

### ISSUE THREAD

**Issue by kentone** [fennifith/Alarmio#127] opened 2020-05-14 21:23 UTC
This was a feature from the LineageOS clock (I think) that I found quite cool, just take note of it if you guys think is cool too :)

Keep the good work 😋

**Comment by fennifith** [comment] 2020-05-15 19:51
I think this is a duplicate of #12 lol

I'll probably work on custom alarm interfaces as a generic extensible thing for a future version, so all the "solve a puzzle to dismiss" / related feature requests will likely be addressed at once.

**Closed** 2020-05-15 19:51 UTC
Labels: duplicate
