### ISSUE TITLE
Same error message after every restart of system and sometimes app

### ISSUE THREAD

**Issue by kreativum** [fennifith/Alarmio#151] opened 2021-03-04 13:42 UTC
## Device Info

- Brand: `Nokia`
- Model name: `6.1`
- Android version: `10, Stock, Android One device`
- Launcher: `Lawnchair 2.0-2589` (maybe it is relevant. idk)
- Alarmio version: `1.0.5`
- Source: `F-Droid`

## Steps to Reproduce

- app installed 
- restart system
- wait for home screen finshined to load
- Alarmio automatically starts and shows the same error message
- shut down Alarmio in multi task view
- Alarmio automatically starts again and shows the same error message

## Error Message

`java.lang.RuntimeException at Alarmio.java:118`

## Stack Trace

`java.lang.RuntimeException: Unable to create application me.jfenn.alarmio.Alarmio: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=me.jfenn.alarmio/.services.TimerService }: app is in background uid UidRecord{8de5092 u0a359 SVC  idle change:idle|uncached procs:1 seq(0,0,0)}
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6484)
 at android.app.ActivityThread.access$1300(ActivityThread.java:220)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
 at android.os.Handler.dispatchMessage(Handler.java:107)
 at android.os.Looper.loop(Looper.java:214)
 at android.app.ActivityThread.main(ActivityThread.java:7397)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=me.jfenn.alarmio/.services.TimerService }: app is in background uid UidRecord{8de5092 u0a359 SVC  idle change:idle|uncached procs:1 seq(0,0,0)}
 at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1616)
 at android.app.ContextImpl.startService(ContextImpl.java:1571)
 at android.content.ContextWrapper.startService(ContextWrapper.java:669)
 at me.jfenn.alarmio.Alarmio.onCreate(Alarmio.java:118)
 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1183)
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6479)
 ... 8 more`

**Comment by fennifith** [comment] 2021-03-12 02:18
I believe this is a duplicate of #113 (although I don't blame you for missing it given the amount of open issues at the moment - hopefully I can do something about that soon...)

**Closed** 2021-03-12 02:18 UTC
Labels: duplicate

**Comment by kreativum** [comment] 2021-03-12 15:41
> 
> 
> I believe this is a duplicate of #113 (although I don't blame you for missing it given the amount of open issues at the moment - hopefully I can do something about that soon...)

Thanks. Usally I don't use code platforms. Didn't knew the right keywords to search for duplicates.
If you or the team need more information on the circumstances, feel free to post here. I'll see what i can do.
